---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: Le tableau de bord bien conçu dans la NetApp Console analyse les configurations système en termes de fiabilité, de sécurité, d’excellence opérationnelle, d’optimisation des coûts et d’efficacité des performances, fournissant des informations et des recommandations pour vous aider à atteindre l’excellence opérationnelle. 
---
= Découvrez le tableau de bord bien conçu dans la NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le tableau de bord bien architecturé dans la NetApp Console vous aide à maintenir et exploiter des configurations fiables, sécurisées, efficaces et économiques, conformes aux frameworks bien architecturés pour le type de stockage que vous utilisez. Le tableau de bord offre une vue unifiée sur l'ensemble des comptes et des régions, aide les équipes à identifier et à hiérarchiser les risques, et prend en charge des règles personnalisées pour des exigences spécifiques. Des analyses quotidiennes automatiques de la configuration de votre système de stockage fournissent des informations et des recommandations pour vous aider à optimiser vos environnements de stockage.



[[how-it-works]]
== Comment ça marche

Le tableau de bord bien architecturé analyse quotidiennement vos configurations. L'analyse fournit l'état bien architecturé, des informations et des recommandations.

Une fois l'analyse quotidienne terminée, les configurations apparaissent comme « optimisées » ou « non optimisées » dans le tableau de bord Well-Architected. Vous trouverez le score d'optimisation total, les problèmes de configuration par catégorie, ainsi qu'une liste des problèmes de configuration et des recommandations. Vous pouvez consulter les recommandations pour les problèmes de configuration. Certains problèmes peuvent être corrigés automatiquement par le tableau de bord Well-Architected, tandis que d'autres nécessitent une intervention manuelle. Dans ce cas, le tableau de bord Well-Architected fournit des instructions détaillées pour vous aider à mettre en œuvre les modifications recommandées.

Vous pouvez ignorer l'analyse des configurations qui ne s'appliquent pas à vos environnements. Cela évite les alertes inutiles et des résultats d'optimisation inexacts. Lorsque vous ignorez une analyse de configuration spécifique, le tableau de bord well-architected n'inclut pas la configuration dans le score d'optimisation total.



[[why-it-matters]]
== Pourquoi c'est important

Le tableau de bord optimisé dans la NetApp Console applique les meilleures pratiques aux environnements de stockage, de bases de données et VMware de grande envergure en combinant une évaluation continue avec des recommandations et des actions correctives. Les actions correctives automatisées appliquées dans le tableau de bord optimisé réduisent les erreurs humaines, garantissent une gestion uniforme et préservent les performances et la fiabilité de vos infrastructures système.



[[supported-storage-systems]]
== Systèmes de stockage pris en charge

Le tableau de bord bien conçu de la Console prend en charge les systèmes de stockage suivants :

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP dans Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Commencez à utiliser la NetApp Console pour détecter et corriger les erreurs de configuration système

Pour commencer à utiliser NetApp Console, inscrivez-vous, ajoutez vos identifiants et établissez une connexion pour gérer vos ressources et optimiser les configurations système.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flux de travail de démarrage pour NetApp Console (application SaaS)"^]



[[related-information]]
== Informations connexes

* link:fsx/improve-configurations-fsx.html["Mettre en œuvre des systèmes de fichiers FSx for ONTAP bien architecturés"^]
* link:cvo/improve-configurations-cvo.html["Implémentez des systèmes Cloud Volumes ONTAP bien architecturés"^]

