---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: Le tableau de bord bien conçu dans la NetApp Console analyse les configurations système en termes de fiabilité, de sécurité, d’excellence opérationnelle, d’optimisation des coûts et d’efficacité des performances, fournissant des informations et des recommandations pour vous aider à atteindre l’excellence opérationnelle. 
---
= Découvrez le tableau de bord bien conçu dans la NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory vous aide à maintenir et à exploiter des configurations fiables, sécurisées, efficaces et économiques, conformes aux architectures éprouvées pour le type de stockage que vous utilisez. Le tableau de bord optimisé dans la NetApp Console offre une vue unifiée des comptes et des régions, aide les équipes à identifier et à prioriser les risques, et prend en charge les règles personnalisées pour des besoins spécifiques. Des analyses quotidiennes automatiques de la configuration de votre système de stockage fournissent des informations et des recommandations pour vous aider à optimiser vos environnements de stockage.



[[how-it-works]]
== Comment ça marche

Workload Factory analyse quotidiennement vos configurations. L'analyse fournit un état bien architecturé, des informations et des recommandations pour vous aider à optimiser vos environnements de stockage.

Une fois l'analyse quotidienne terminée, les configurations apparaissent comme « optimisées » ou « non optimisées » dans le tableau de bord Well-Architected. Vous trouverez les problèmes de configuration classés par catégorie du cadre Well-Architected (fiabilité, sécurité, excellence opérationnelle, optimisation des coûts et efficacité des performances), ainsi qu'une liste de problèmes de configuration et de recommandations. Workload Factory peut corriger certains problèmes automatiquement, tandis que d'autres nécessitent une intervention manuelle. Dans ce cas, la recommandation fournit des instructions détaillées pour vous aider à mettre en œuvre les modifications.

Vous pouvez ignorer l'analyse des configurations qui ne s'appliquent pas à vos environnements. Ignorer les configurations permet d'éviter les alertes inutiles et les résultats d'optimisation inexacts.



[[why-it-matters]]
== Pourquoi c'est important

Workload Factory applique les meilleures pratiques aux environnements de stockage, de bases de données et VMware de grande envergure en combinant une évaluation continue avec des recommandations et des actions correctives. La correction automatisée réduit les erreurs humaines, garantit une gestion uniforme et préserve les performances et la fiabilité de vos infrastructures système.



[[supported-storage-systems]]
== Systèmes de stockage pris en charge

Le tableau de bord bien conçu de la Console prend en charge les systèmes de stockage suivants :

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP dans Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Commencez à utiliser la NetApp Console pour détecter et corriger les erreurs de configuration système

Pour commencer à utiliser NetApp Console, inscrivez-vous, ajoutez vos identifiants et établissez une connexion pour gérer vos ressources et optimiser les configurations système.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flux de travail de démarrage pour NetApp Console (application SaaS)"^]



[[related-information]]
== Informations connexes

* link:fsx/improve-configurations-fsx.html["Mettre en œuvre des systèmes de fichiers FSx for ONTAP bien architecturés"^]
* link:cvo/improve-configurations-cvo.html["Implémentez des systèmes Cloud Volumes ONTAP bien architecturés"^]

