---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: Découvrez les nouveautés du tableau de bord bien conçu dans la NetApp Console. 
---
= Quelles sont les nouveautés concernant le tableau de bord bien conçu dans la NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés du tableau de bord bien conçu dans la NetApp Console.



[[17-august-2026]]
== 17 août 2026



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Prise en charge de Google Cloud NetApp Volumes dans le tableau de bord bien architecturé

Le tableau de bord de la NetApp Console prend désormais en charge Google Cloud NetApp Volumes. Les administrateurs de stockage peuvent consulter l’état de leurs pools de stockage et de leurs configurations, obtenir des recommandations pour améliorer l’efficacité, le coût, les performances, la fiabilité et la sécurité, et prendre des mesures pour optimiser les opérations et suivre les bonnes pratiques.

En savoir plus sur link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Analyse de configuration pour Google Cloud NetApp Volumes"].



[[03-august-2026]]
== 03 août 2026



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure

Le tableau de bord bien conçu dans la NetApp Console vous permet désormais de corriger les recommandations de configuration pour vos systèmes Cloud Volumes ONTAP.

Vous pouvez également exclure une ou plusieurs configurations de l'analyse d'architecture bien conçue. Cela vous permet d'ignorer les configurations qui ne s'appliquent pas à votre environnement.

Si vous souhaitez réintégrer ultérieurement une configuration rejetée, vous pouvez la réactiver dans le tableau de bord bien architecturé. Cela rétablit la configuration dans l’analyse et vous permet d’obtenir des recommandations et des correctifs pour celle-ci.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure"]



[[20-july-2026]]
== 20 juillet 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Présentation du tableau de bord bien conçu dans NetApp Console

Le tableau de bord bien architecturé dans la NetApp Console offre une vue unique de vos systèmes de stockage et de leurs configurations, tous comptes et régions confondus. Le tableau de bord fournit des informations et des recommandations pour vous aider à atteindre l'excellence opérationnelle. Vous pouvez consulter l'état bien architecturé de vos configurations, les problèmes de configuration organisés selon les piliers du cadre bien architecturé pour le type de stockage que vous utilisez, ainsi qu'une liste des problèmes de configuration et des recommandations.

Apprenez-en davantage sur le link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["tableau de bord bien conçu"].

Le tableau de bord bien conçu de la Console est disponible pour link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Cloud Volumes ONTAP dans Microsoft Azure."]



[[build-your-own-custom-rules]]
=== Créez vos propres règles personnalisées

Rédigez des règles personnalisées en langage clair pour garantir que vos systèmes respectent les normes de votre organisation et les bonnes pratiques NetApp. Testez les règles avec une exécution à blanc, puis planifiez leur exécution dans vos environnements.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["En savoir plus sur les règles personnalisées"]
