---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: Découvrez les nouveautés du tableau de bord bien conçu dans la NetApp Console. 
---
= Quelles sont les nouveautés concernant le tableau de bord bien conçu dans la NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés du tableau de bord bien conçu dans la NetApp Console.



[[17-august-2026]]
== 17 août 2026



[[fsx-for-ontap-support-in-the-well-architected-dashboard-in-netapp-console]]
=== Prise en charge de FSx for ONTAP dans le tableau de bord bien conçu de la NetApp Console

Le tableau de bord bien conçu dans la NetApp Console est disponible pour Amazon FSx for NetApp ONTAP.

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Découvrez l'analyse de configuration pour FSx for ONTAP"]




[[updated-configuration-names-for-fsx-for-ontap-in-the-well-architected-dashboard]]
=== Noms de configuration mis à jour pour FSx for ONTAP dans le tableau de bord bien architecturé

Le tableau de bord bien conçu dans la NetApp Console inclut désormais de nouveaux noms de configuration de stockage pour FSx for ONTAP.

Le tableau suivant répertorie les anciens noms de configuration et leurs nouveaux noms de configuration correspondants dans le tableau de bord bien architecturé.

[cols="1,1"]
|===
| Ancien nom de configuration | Nouveau nom de configuration 


| Planifiez les sauvegardes des volumes | Sauvegardes de volumes 


| seuil de capacité SSD | marge de capacité SSD 


| Seuil de capacité des fichiers | Marge de capacité des fichiers 


| Fiabilité des données de conservation à long terme | Étiquettes de politique de réplication 


| Instantanés locaux programmés | Stratégie de snapshot 


| Supprimez les sauvegardes inutiles | Expiration de la sauvegarde 


| Supprimer les instantanés inutiles | Expiration de l'instantané 


| Capacité SSD sous-utilisée | Capacité SSD surdimensionnée 


| Périphériques de bloc inactifs | Périphériques de blocs inactifs (LUN) 


| Optimisez le TCO en hiérarchisant les données froides | Hiérarchisation des données froides 


| Rapport de capacité logique de volume | Rapports de capacité visibles par l'hôte 


| FlexGroup volumes rééquilibrage | Rééquilibrer les volumes FlexGroup 


| FlexVol rééquilibrage des volumes | Rééquilibrer les volumes FlexVol 


| Mode d'écriture de la relation de cache | FlexCache mode d'écriture 


| Optimiser la taille du volume de cache | FlexCache taille de la réplique 


| Accès non autorisé au volume | Accès non autorisé au volume iSCSI 


| ARP/AI désactivé | Protection contre les ransomwares (ARP/IA) 
|===


[[well-architected-issues-displayed-in-netapp-console-systems-page]]
=== Problèmes bien architecturés affichés sur la page Systèmes de NetApp Console

Les notifications relatives aux problèmes d'architecture sont disponibles pour Cloud Volumes ONTAP dans Microsoft Azure depuis la page Systèmes de gestion du stockage dans la NetApp Console. Cette fonctionnalité vous aide à identifier rapidement les problèmes de configuration dans vos systèmes Cloud Volumes ONTAP dans Azure et à accéder au tableau de bord bien architecturé des charges de travail directement depuis la notification.



[[10-august-2026]]
== 10 août 2026



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Prise en charge de Google Cloud NetApp Volumes dans le tableau de bord bien architecturé

Le tableau de bord de la NetApp Console prend désormais en charge Google Cloud NetApp Volumes. Les administrateurs de stockage peuvent consulter l’état de leurs pools de stockage et de leurs configurations, obtenir des recommandations pour améliorer l’efficacité, le coût, les performances, la fiabilité et la sécurité, et prendre des mesures pour optimiser les opérations et suivre les bonnes pratiques.

En savoir plus sur link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Analyse de configuration pour Google Cloud NetApp Volumes"].



[[03-august-2026]]
== 03 août 2026



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure

Le tableau de bord bien conçu dans la NetApp Console vous permet désormais de corriger les recommandations de configuration pour vos systèmes Cloud Volumes ONTAP.

Vous pouvez également exclure une ou plusieurs configurations de l'analyse d'architecture bien conçue. Cela vous permet d'ignorer les configurations qui ne s'appliquent pas à votre environnement.

Si vous souhaitez réintégrer ultérieurement une configuration rejetée, vous pouvez la réactiver dans le tableau de bord bien architecturé. Cela rétablit la configuration dans l’analyse et vous permet d’obtenir des recommandations et des correctifs pour celle-ci.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure"]



[[20-july-2026]]
== 20 juillet 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Présentation du tableau de bord bien conçu dans NetApp Console

Le tableau de bord bien architecturé dans la NetApp Console offre une vue unique de vos systèmes de stockage et de leurs configurations, tous comptes et régions confondus. Le tableau de bord fournit des informations et des recommandations pour vous aider à atteindre l'excellence opérationnelle. Vous pouvez consulter l'état bien architecturé de vos configurations, les problèmes de configuration organisés selon les piliers du cadre bien architecturé pour le type de stockage que vous utilisez, ainsi qu'une liste des problèmes de configuration et des recommandations.

Apprenez-en davantage sur le link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["tableau de bord bien conçu"].

Le tableau de bord bien conçu de la Console est disponible pour link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Cloud Volumes ONTAP dans Microsoft Azure."]



[[build-your-own-custom-rules]]
=== Créez vos propres règles personnalisées

Rédigez des règles personnalisées en langage clair pour garantir que vos systèmes respectent les normes de votre organisation et les bonnes pratiques NetApp. Testez les règles avec une exécution à blanc, puis planifiez leur exécution dans vos environnements.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["En savoir plus sur les règles personnalisées"]
