= Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure
:allow-uri-read: 




[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure

Le tableau de bord bien conçu dans la NetApp Console vous permet désormais de corriger les recommandations de configuration pour vos systèmes Cloud Volumes ONTAP.

Vous pouvez également exclure une ou plusieurs configurations de l'analyse d'architecture bien conçue. Cela vous permet d'ignorer les configurations qui ne s'appliquent pas à votre environnement.

Si vous souhaitez réintégrer ultérieurement une configuration rejetée, vous pouvez la réactiver dans le tableau de bord bien architecturé. Cela rétablit la configuration dans l’analyse et vous permet d’obtenir des recommandations et des correctifs pour celle-ci.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corrigez, ignorez et réactivez les configurations pour Cloud Volumes ONTAP dans Microsoft Azure"]
