---
sidebar: sidebar 
permalink: gcnv/configuration-analysis-gcnv.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: 'NetApp Console analyse régulièrement la configuration des systèmes de stockage afin de détecter d"éventuels problèmes.' 
---
= Analyse de configuration pour Google Cloud NetApp Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le tableau de bord Well-Architected dans NetApp Console vérifie régulièrement les paramètres de votre système de stockage afin de détecter d'éventuels problèmes. S'il détecte des problèmes, il indique de quoi il s'agit et explique comment les résoudre afin que vos systèmes de stockage offrent de bonnes performances, maîtrisent les coûts et respectent les bonnes pratiques, aussi bien en mode par défaut qu'en mode ONTAP pour les environnements Flex Unified Google Cloud NetApp Volumes.

Principales fonctionnalités :

* Analyse quotidienne de la configuration
* Validations automatiques des bonnes pratiques pour les systèmes de stockage NetApp ONTAP et les fournisseurs de stockage partenaires
* Observabilité proactive
* Des idées à l'action




[[analysis-requirements]]
== Exigences d'analyse

Pour une analyse complète du pool de stockage, vous devez procéder comme suit :

* link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-create-system.html["Ajoutez votre système Google Cloud NetApp Volumes à la NetApp Console"^].
* Accordez les autorisations de _visualisation, de planification et d'analyse_ dans votre compte Google Cloud.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Découvrez comment accorder des autorisations à un compte Google Cloud"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Meilleures pratiques et recommandations pour les charges de travail de stockage

Workload Factory évalue les configurations de stockage par rapport aux bonnes pratiques de stockage et d’ONTAP, ainsi qu’au cadre Google Cloud Well-Architected. L’évaluation recommande également des améliorations pour les ressources Google Cloud NetApp Volumes en mode Default et les ressources Flex Unified découvertes via le point de terminaison proxy de l’API ONTAP.

L'analyse bien architecturée catégorise les configurations selon les piliers suivants du cadre : _fiabilité_ et _excellence opérationnelle_. Les résultats de l'évaluation peuvent inclure une valeur de mode de _Default-mode_ ou _ONTAP-mode_.



[[reliability]]
=== Fiabilité

La fiabilité garantit que les charges de travail exécutent leurs fonctions prévues correctement et de manière constante, même en cas de perturbations.

* *Politique d'instantané*
+
Planifiez des instantanés locaux pour une sauvegarde efficace et une restauration rapide. Les instantanés sont des images instantanées, à un moment donné, de vos volumes.

* *Marge de capacité SSD*
+
Workload Factory recommande de maintenir l’utilisation du niveau SSD à 80 % ou moins. Certaines charges de travail peuvent nécessiter une marge de capacité supplémentaire et des objectifs d’utilisation plus faibles. Lorsque l’utilisation dépasse la marge recommandée, le risque de ralentissements des performances et de problèmes de service augmente, en particulier si la capacité n’est pas étendue à temps. Vous pouvez ignorer cette alerte pour un ou plusieurs pools de stockage et la réactiver ultérieurement si nécessaire.





[[operational-excellence]]
=== Excellence opérationnelle

L'excellence opérationnelle vise à fournir l'architecture la plus optimale et la valeur commerciale.

* *Capacité maximale du volume*
+
Workload Factory recommande de maintenir l'utilisation des volumes en dessous de 80 % afin de réduire le risque de saturation de l'espace. Si un volume croît plus rapidement que prévu, il peut être nécessaire de l'étendre rapidement. Cela peut accroître le risque d'impact sur les applications, notamment en cas de croissance soudaine ou irrégulière. Ce risque est moindre avec le provisionnement fin et la gestion de la capacité. Vous pouvez désactiver cette fonctionnalité pour un ou plusieurs volumes et la réactiver ultérieurement si nécessaire.



.Et ensuite
link:improve-configurations-gcnv.html["Implémentez des configurations Google Cloud NetApp Volumes bien architecturées"]
