---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: 'Le tableau de bord bien conçu analyse régulièrement les configurations du système de fichiers FSx for ONTAP afin de déterminer s"il existe des problèmes de configuration.' 
---
= Analyse de configuration pour Amazon FSx for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le tableau de bord bien conçu dans la NetApp Console analyse régulièrement les configurations du système de stockage afin de déterminer s'il existe des problèmes de configuration avec vos systèmes de fichiers Amazon FSx for NetApp ONTAP. Lorsque des problèmes sont détectés, le tableau de bord vous indique quels sont ces problèmes et explique les modifications à apporter pour garantir que vos systèmes de stockage atteignent des performances optimales, une efficacité des coûts et la conformité aux bonnes pratiques.

Principales fonctionnalités :

* Analyse quotidienne de la configuration
* Validations automatiques des bonnes pratiques pour les systèmes de stockage NetApp ONTAP et les fournisseurs de stockage partenaires
* Observabilité proactive
* Des idées à l'action


Directive non résolue dans <stdin> - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== Exigences d'analyse

Pour une analyse complète du système de fichiers, vous devez procéder comme suit :

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Déployer un agent NetApp Console"^] ou link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["associer un lien"^] pour établir une connectivité entre le système de fichiers et NetApp Console.
* Accordez les autorisations de _visualisation, de planification et d'analyse_ dans votre compte AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Découvrez comment accorder des autorisations à un compte AWS"^]



Directive non résolue dans <stdin> - include::fsx-configurations.adoc[]

.Et ensuite
link:improve-configurations-fsx.html["Implémentez des configurations de système de fichiers Amazon FSx for NetApp ONTAP bien architecturées"]
